package com.xworkz.player.Enum;

public enum SportType {

	CRICKET, VOLLEY_BALL, BADMINTON, CHESS, KABBADI, TENNIS, GOLF, TABLE_TENNIS, 
	SQASH, ATHLETICS, RUGBY, BASKET_BALL, SOCCER, SWIMMING, GYMNASTICS;
}
